### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by Matvey-Kuk** [dzaporozhets/gitlab-time-tracking#4]
Hello!

I'm trying to install tracker and have trouble in step: 
bundle exec rake db:setup --trace

Log:
rake aborted!
Psych::SyntaxError: (<unknown>): mapping values are not allowed in this context at line 9 column 12
/usr/local/rvm/rubies/ruby-2.0.0-p643/lib/ruby/2.0.0/psych.rb:205:in `parse'
/usr/local/rvm/rubies/ruby-2.0.0-p643/lib/ruby/2.0.0/psych.rb:205:in`parse_stream'
/usr/local/rvm/rubies/ruby-2.0.0-p643/lib/ruby/2.0.0/psych.rb:153:in `parse'
/usr/local/rvm/rubies/ruby-2.0.0-p643/lib/ruby/2.0.0/psych.rb:129:in`load'
/usr/local/rvm/gems/ruby-2.0.0-p643/gems/sinatra-activerecord-2.0.1/lib/sinatra/activerecord.rb:32:in `database_file='
/usr/local/rvm/gems/ruby-2.0.0-p643/gems/sinatra-1.4.5/lib/sinatra/base.rb:1208:in`set'
/usr/local/rvm/gems/ruby-2.0.0-p643/gems/sinatra-activerecord-2.0.1/lib/sinatra/activerecord.rb:20:in `registered'
/usr/local/rvm/gems/ruby-2.0.0-p643/gems/sinatra-1.4.5/lib/sinatra/base.rb:1391:in`block in register'
/usr/local/rvm/gems/ruby-2.0.0-p643/gems/sinatra-1.4.5/lib/sinatra/base.rb:1389:in `each'
/usr/local/rvm/gems/ruby-2.0.0-p643/gems/sinatra-1.4.5/lib/sinatra/base.rb:1389:in`register'
/usr/local/rvm/gems/ruby-2.0.0-p643/gems/sinatra-contrib-1.4.2/lib/sinatra/reloader.rb:322:in `register'
/usr/local/rvm/gems/ruby-2.0.0-p643/gems/sinatra-1.4.5/lib/sinatra/base.rb:1970:in`register'
/usr/local/rvm/gems/ruby-2.0.0-p643/gems/sinatra-1.4.5/lib/sinatra/base.rb:2032:in `register'
/usr/local/rvm/gems/ruby-2.0.0-p643/gems/sinatra-activerecord-2.0.1/lib/sinatra/activerecord.rb:53:in`module:Sinatra'
/usr/local/rvm/gems/ruby-2.0.0-p643/gems/sinatra-activerecord-2.0.1/lib/sinatra/activerecord.rb:10:in `<top (required)>'
/root/gitlab-time-tracking/app.rb:30:in`require'
/root/gitlab-time-tracking/app.rb:30:in `<class:GitLabTimeTracking>'
/root/gitlab-time-tracking/app.rb:15:in`<top (required)>'
/root/gitlab-time-tracking/Rakefile:4:in `require'
/root/gitlab-time-tracking/Rakefile:4:in`<top (required)>'
/usr/local/rvm/gems/ruby-2.0.0-p643/gems/rake-10.3.1/lib/rake/rake_module.rb:28:in `load'
/usr/local/rvm/gems/ruby-2.0.0-p643/gems/rake-10.3.1/lib/rake/rake_module.rb:28:in`load_rakefile'
/usr/local/rvm/gems/ruby-2.0.0-p643/gems/rake-10.3.1/lib/rake/application.rb:683:in `raw_load_rakefile'
/usr/local/rvm/gems/ruby-2.0.0-p643/gems/rake-10.3.1/lib/rake/application.rb:94:in`block in load_rakefile'
/usr/local/rvm/gems/ruby-2.0.0-p643/gems/rake-10.3.1/lib/rake/application.rb:176:in `standard_exception_handling'
/usr/local/rvm/gems/ruby-2.0.0-p643/gems/rake-10.3.1/lib/rake/application.rb:93:in`load_rakefile'
/usr/local/rvm/gems/ruby-2.0.0-p643/gems/rake-10.3.1/lib/rake/application.rb:77:in `block in run'
/usr/local/rvm/gems/ruby-2.0.0-p643/gems/rake-10.3.1/lib/rake/application.rb:176:in`standard_exception_handling'
/usr/local/rvm/gems/ruby-2.0.0-p643/gems/rake-10.3.1/lib/rake/application.rb:75:in `run'
/usr/local/rvm/gems/ruby-2.0.0-p643/gems/rake-10.3.1/bin/rake:33:in`<top (required)>'
/usr/local/rvm/gems/ruby-2.0.0-p643/bin/rake:23:in `load'
/usr/local/rvm/gems/ruby-2.0.0-p643/bin/rake:23:in`<main>'
/usr/local/rvm/gems/ruby-2.0.0-p643/bin/ruby_executable_hooks:15:in `eval'
/usr/local/rvm/gems/ruby-2.0.0-p643/bin/ruby_executable_hooks:15:in`<main>'

How do you think, what's the reason?

**Comment by StephenOTT** [comment]
Will have a look this week.  Just traveling atm.
